config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#createfb'
  get 'auth/failure', to: redirect('/')  
  get 'logout', to: 'sessions#destroyfb'

  get 'sessions/new'
  root 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :results, only: [:create]
  resources :time_infos, only: [:create]
  resources :tests , only: [:new]
  resources :users
  namespace :admin , shallow: true do 
    resources :grades, only: [:show, :index, :destroy] 
      
    resources :questions, only: [:new, :new2, :new3, :index, :create, :destroy, :edit, :update]
    resources :users do 
      member do 
        patch :block, :unblock
        get :review 
      end
    end
    resources :subjects do 
      member do 
        patch :opening, :closed
      end
    end
    resources :user_subjects do 
      member do 
        get :add_user
        patch :update_user
      end
    end 
  end 

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	enum status: [ "Ready", "Started" ] 
	has_many :subject_dones, dependent: :destroy
	has_many :user_subjects, dependent: :destroy
	has_many :users, through: :user_subjects
	validates :title, presence: true, uniqueness: true
	validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
	has_many :questions, dependent: :destroy
	has_many :tests, dependent: :destroy
	has_many :grades, dependent: :destroy
	has_many :time_infos, dependent: :destroy
	after_create :update_status

	def update_status
		self.update_attributes(status: "Ready")
	end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :admin_user
  def new
  	@subject = Subject.new
  end

  def show
  	@subject = Subject.find(params[:id])
    @questions = @subject.questions
  end
 	 
  def index
  	@search = Subject.search(params[:q])
    @subjects = @search.result  
  end

  def edit
  	@subject = Subject.find(params[:id])
  end

  def create
  	@subject = Subject.new(subject_params)
  	if @subject.save
  		flash[:success] = "added a subject"
  		redirect_to new_admin_question_path(subject: @subject.id)
  	else
  		render 'new'
  	end
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      flash[:success] = "a subject updated!"
      redirect_to admin_subjects_url
    else
      render 'edit'
    end
  end

  def opening
    @subject = Subject.find(params[:id])
    @subject.update_attributes(update_status_params) 
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def closed
    @subject = Subject.find(params[:id])
    @subject.update_attributes(update_status_params) 
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def destroy
  	Subject.find(params[:id]).destroy  
    flash[:success] = "subject deleted!"
    redirect_to admin_subjects_url
  end

  private

  def subject_params
  	params.require(:subject).permit(:title, :duration)
  end

  def update_status_params
    params.require(:subject).permit(:status)
  end
end

app/views/admin/subjects/_available.html.erb
<% if @user.finished?(subject) %>
	<strong><%= "Finished" %></strong>
<% else %>			  
	<%= form_for TimeInfo.new do |f| %>
		<%= f.hidden_field :subject_id, value: subject.id %>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.submit "START", class: "btn btn-primary" %>
	<% end %>
<% end %>
	
	
	 

app/views/admin/subjects/_closed.html.erb
<%= form_for subject, url: closed_admin_subject_path(subject), remote: true do |f| %>
	<%= f.hidden_field :status, value: "Started" %>
	<strong><%= f.submit "Closed" %></strong>
<% end %>

app/views/admin/subjects/_finish.html.erb
	<% if @user.finished?(subject) %>
		<strong><%= "Finished" %></strong>
	<% end %>		
	

app/views/admin/subjects/_opening.html.erb
<%= form_for subject, url: opening_admin_subject_path(subject), remote: true do |f| %>
	<%= f.hidden_field :status, value: "Ready" %>
	<%= f.submit "Opening", class: "btn btn-success" %>
<% end %>

app/views/admin/subjects/_unavailable.html.erb
<strong><%= "This test is NOT available now." %></strong>

app/views/admin/subjects/closed.js.erb
$("#active-<%= @subject.id %>").html("<%= escape_javascript(render partial: 'opening', locals: {subject: @subject}) %>");

app/views/admin/subjects/edit.html.erb
<% provide(:title, 'Subject') %>
<h1> Edit subject </h1> 

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for [:admin, @subject] do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control'%>
			
			<%= f.label :Time_for_this_subject %> (minutes)
			<%= f.text_field :duration, class: 'form-control'%>
			<div class="action">
				<%= f.submit "Save", class: "btn btn-primary" %>
			</div>	
		<% end %>	
	</div>	
</div>

app/views/admin/subjects/index.html.erb
<% provide(:title, 'Subject list') %>
<h1> Subject list</h1>	
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="action">
			<%= link_to "New subject", new_admin_subject_path, class: "btn btn-success" %>
		</div>	
		<table border="1" style="width:100%">	
		  
		  <tr>
		    <th>index</th>
		    <th><%= sort_link @search, :title, "subject" %></th>		
		    <th>number of questions</th>
		    <th><%= sort_link @search, :duration, "time (minutes)" %></th>
		    <th>examinees</th>
		    <th>actions</th>
		    <th>status</th>
		  </tr>
		  <% @subjects.each.with_index(1) do |subject, index| %>
		  <tr>
		    <td><%= "#{index}" %></td>   	
		    <td><%= link_to subject.title, admin_subject_path(subject) %></td>
		    <td><%= subject.questions.count  %></td> 	
		    <td><%= link_to subject.duration, edit_admin_subject_path(subject) %></td>
		    <td><%= link_to subject.users.count, admin_user_subject_path(subject) %></td>
		    <td><%# link_to "Add users ", admin_user_subject_path(subject) %>
		    	<%= link_to " Edit", edit_admin_subject_path(subject) %>
		    	|<%= link_to " View", admin_subject_path(subject) %>
		  		|<%= link_to " Delete", admin_subject_path(subject), method: :delete, data: { confirm: " You sure?" } %>
		  		|<%= link_to " Add question", new_admin_question_path(subject: subject.id) %>
		  	</td> 
		  	<td> 
		  		<div id="active-<%= subject.id %>", class="button">
			  		<% case subject.status %> 
			  		<% when "Started"  %>	
			  			<%= render partial: 'opening', locals: {subject: subject} %>
			  		<% when "Ready" %>
			  			<%= render partial: 'closed', locals: {subject: subject} %>
			  		<%# when "Finish"  %>	
			  			<%# render partial: 'opening', locals: {subject: subject} %>	
			  		<% end %>
			  	</div>	
		  	</td>
		  </tr> 
		  <% end %>
		</table>
	</div>
</div>	

app/views/admin/subjects/new.html.erb
<% provide(:title, 'Subject') %>
<h1> add subject </h1> 

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for [:admin, @subject] do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control'%>
			
			<%= f.label :Time_for_this_subject %> (minutes)
			<%= f.text_field :duration, class: 'form-control'%>
			<div class="action">
				<%= f.submit "Create subject", class: "btn btn-primary" %>
			</div>	
		<% end %>	
	</div>	
</div>

app/views/admin/subjects/opening.js.erb
$("#active-<%= @subject.id %>").html("<%= escape_javascript(render partial: 'closed', locals: {subject: @subject}) %>");

app/views/admin/subjects/show.html.erb
<% provide(:title, 'subject') %>
<h1><%= @subject.title  %></h1>	
<div class="row">
	<div class="col-md-12 ">
		 Number of questions: <%= @questions.count %><br>
		 Duration: <%= @subject.duration %> (minutes)
		 <%= link_to "Add question", new_admin_question_path(subject: @subject.id) %>
		<table border="1" style="width:100%"> 
		  <tr>
		    <th>index</th>
		    <th>question</th>		
		    <th> answers</th>
		    <th>action</th>
		  </tr>
		  <% @questions.each.with_index(1) do |question, index| %>
		  <tr>
		    <td><%= "#{index}" %></td>   	
		    <td>
	    		<%= simple_format question.content %><br>
	    		<%= image_tag question.picture.url if question.picture? %>
		    </td>
		    <td>
		    	<ul>
		    		<% if question.inactive? %>
		    			<p style="color:red"><%= "This question is inactive." %></p>
		    			<%# link_to "Edit", edit_admin_question_path(subject: question.subject_id) %>		
		    		<% else %>	
			    		<% question.answers.each do |answer| %>
			    			<% if answer.correct_answer %>
			    				<div id="correct" >
			    					<li><%= answer.content %><br>
			    						<%= image_tag answer.picture.url if answer.picture? %>
			    					</li>
			    				</div>
			    			<% else %>
			    				<li><%= answer.content %><br>
			    					<%= image_tag answer.picture.url if answer.picture? %>
			    				</li>
			    			<% end %>	
		    			<% end %>		
		    		<% end %>	
		    	</ul>
		    </td> 
		    <td>
		  		<%= link_to "Delete", admin_question_path(question), method: :delete, data: { confirm: "You sure?" } %>
		  	</td> 
		  </tr> 
		  <% end %>

		</table>
		
	</div>
</div>	