config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#createfb'
  get 'auth/failure', to: redirect('/')  
  get 'logout', to: 'sessions#destroyfb'

  get 'sessions/new'
  root 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :results, only: [:create]
  resources :time_infos, only: [:create]
  resources :tests , only: [:new]
  resources :users
  namespace :admin , shallow: true do 
    resources :grades, only: [:show, :index, :destroy] 
      
    resources :questions, only: [:new, :new2, :new3, :index, :create, :destroy, :edit, :update]
    resources :users do 
      member do 
        patch :block, :unblock
        get :review 
      end
    end
    resources :subjects do 
      member do 
        patch :opening, :closed
      end
    end
    resources :user_subjects do 
      member do 
        get :add_user
        patch :update_user
      end
    end 
  end 

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subject_dones, dependent: :destroy
  has_many :time_infos, dependent: :destroy
  has_many :login_attempts, dependent: :destroy
  has_many :user_subjects, dependent: :destroy
  has_many :subjects, through: :user_subjects
  has_many :grades, dependent: :destroy
  has_many :results, dependent: :destroy
	has_many :tests, dependent: :destroy
  attr_accessor :remember_token, :reset_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def finished?(subject)
    SubjectDone.where(subject_id: subject.id, user_id: self.id).count > 0
  end

  def send_password
    UserMailer.send_mail(self).deliver_now
  end
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      # user.oauth_token = auth.credentials.token
      # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.password = SecureRandom.urlsafe_base64      
      user.save!
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user 
  before_action :logged_in_user 

  def review
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def index
    @search = User.search(params[:q])
    @users = @search.result.where(admin: false).paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @subjects = @user.subjects
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_password
      flash[:success] = "#{@user.name} has been added ."
      redirect_to admin_users_url
    else
      render 'new'
    end  
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted!"
    redirect_to admin_users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :phone, :admin)
    end

    def user_status_params
      params.require(:user).permit(:status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user 
  before_action :correct_user, only: [:show]

  def show
    @user = User.find(params[:id])
    @subjects = @user.subjects
    # redirect_on_back_to login_path
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(user_params)
  #     flash[:success] = "Your password has been updated ."
  #     redirect_to current_user
  #   else
  #     flash[:danger] = "Opps, something wrong ."
  #     render 'edit'
  #   end

  # end

  private
  
  # def user_params
  #   params.require(:user).permit(:password, :password_confirmation)  
  # end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(current_user) unless current_user?(@user)
  end
end

app/views/admin/users/_block.html.erb
<%= form_for user, url: unblock_admin_user_path(user), remote: true do |f| %>
	<%= f.hidden_field :status, value: false %>
	<%= f.submit "Unblock", class: "btn btn-danger" %>
<% end %>	

app/views/admin/users/_unblock.html.erb
<%= form_for user, url: block_admin_user_path(user), remote: true do |f| %>
	<%= f.hidden_field :status, value: true %>
	<%= f.submit "Block this user", class: "btn btn-warning" %>
<% end %>	

app/views/admin/users/block.js.erb
$("#block-<%= @user.id %>").html("<%= escape_javascript(render partial: 'block', locals: {user: @user}) %>");

app/views/admin/users/edit.html.erb
<% provide(:title, 'Sign up') %>
<h1>Update</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @user] do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <div class="action">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, 'Users') %>
<h1> Manage users </h1>	
<div class="row"> 
	<div class="col-md-8 col-md-offset-2">
		<div class="action">
			<%= link_to "New user", new_admin_user_path, class: "btn btn-success" %>
		</div>	
		<%= will_paginate %>
		<table border="1" style="width:100%">	
		  <tr>
		  	<th>index</th>
		    <th><%= sort_link @search, :name, "user name" %></th>		
		    <th> subjects</th>
		    <th>actions</th>
		    <!-- <th>status</th> -->
		  </tr>
		  <% @users.each.with_index(1) do |user, index| %>	
			  <tr> 
			  	<td><%= "#{index}"%></td>  	
			    <td><%= user.name %></td>
			    <td>
			    	<% user.subjects.each do |subject| %>
			    		<%= link_to subject.title, admin_user_subject_path(subject) %>,
			    	<% end %>			
			    </td>
			    <td>	
			    	<%= link_to " Add subjects ", add_user_admin_user_subject_path(user) %>
				    | <%= link_to " Edit  ", edit_admin_user_path(user) %>
				  	| <%= link_to " Delete ", admin_user_path(user), method: :delete, data: { confirm: "You sure?" } %>
				  	| <%= link_to " View Score", review_admin_user_path(user) %>
				  </td>		
			 
			  	<!-- <td>
			  		<div id="block-<%= user.id %>", class="button">
			  			<%# if user.status || user.login_limit? %>
			  				<%# render partial: 'block', locals: {user: user} %>	
			  			<%# else %>	
			  				<%# render partial: 'unblock', locals: {user: user}%>	
			  			<%# end %>
		  			</div>
			  	</td> -->
	  		</tr> 	
		  <% end %>
		  
		</table>
		<%= will_paginate %>
	</div>
</div>	

app/views/admin/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>add user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @user] do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%# f.label :password %>
      <%= f.hidden_field :password, value: SecureRandom.hex(4) %>

      <%# f.label :password_confirmation, "Confirmation" %>
      <%# f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :admin, 'Is this admin?' %>
      <%= f.select :admin, options_for_select(['false', 'true']) %><br>
      
      <div class="action">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/admin/users/review.html.erb
<% provide(:title, 'Score') %>
<h1> review</h1>	
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		User name: <strong><%= @user.name %></strong>
		<table border="1" style="width:100%">	
		  <tr>	
		  	<th>index</th>
		    <th>subject</th>	
		    <th>score</th> 
		    <th>time</th>
		    <th>actions</th>
		  </tr>
		  <% @user.grades.each.with_index(1) do |grade, index| %>
		  	<%# if !grade.subject.nil? %>
				  <tr>
				  	<td><%= "#{index}" %></td>   	
				    <td><%= grade.subject.title %></td>
				    <td><%= link_to grade.score, admin_grade_path(grade) %></td> 
				    <td><%= time_ago_in_words(grade.created_at) %> ago</td>
				    <td>
				  		<%= link_to "Delete", admin_grade_path(grade), method: :delete, data: { confirm: "You sure?" } %>
				  	</td> 
		  		</tr> 	
		  	<%#end%>	
		  <% end %> 
		</table>
	</div>
</div>	

app/views/admin/users/show.html.erb
<% provide(:title, 'Subject list') %>
<h1> Test</h1>	
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<table border="1" style="width:100%">	
		  <tr>
		    <th>index</th>
		    <th>subject</th>		
		    <th>number of questions</th>
		    <th>time</th>
		    <th>Status</th>
		  </tr>
		  <% @subjects.each.with_index(1) do |subject, index| %>
		  <tr> 
		    <td><%= "#{index}" %></td>   	
		    <td><%= subject.title %></td>
		    <td><%= 20  %></td> 	
		    <td><%= subject.duration %> minutes</td>
		    <td>
			    <div id="status-<%= subject.id %>">
			    	<% case subject.status %>
			    	<% when "Started" %>
			    		<%= render partial: 'admin/subjects/available', locals: {subject: subject} %>
			    	<% when "Ready" %>
			    		<%= render 'admin/subjects/unavailable' %>
			    	<% end %>
			    </div>	
		    </td>
		  </tr> 
		  <% end %>
		</table>
	</div>
</div>	

app/views/admin/users/unblock.js.erb
$("#block-<%= @user.id %>").html("<%= escape_javascript(render partial: 'unblock', locals: {user: @user}) %>");