config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#createfb'
  get 'auth/failure', to: redirect('/')  
  get 'logout', to: 'sessions#destroyfb'

  get 'sessions/new'
  root 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :results, only: [:create]
  resources :time_infos, only: [:create]
  resources :tests , only: [:new]
  resources :users
  namespace :admin , shallow: true do 
    resources :grades, only: [:show, :index, :destroy] 
      
    resources :questions, only: [:new, :new2, :new3, :index, :create, :destroy, :edit, :update]
    resources :users do 
      member do 
        patch :block, :unblock
        get :review 
      end
    end
    resources :subjects do 
      member do 
        patch :opening, :closed
      end
    end
    resources :user_subjects do 
      member do 
        get :add_user
        patch :update_user
      end
    end 
  end 

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>        
      <% if current_user.admin? %>
        <%= link_to "kaopiz", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li title= "Subjects"><%= link_to "Subjects", admin_subjects_path %></li> 
            <li title= "Users"><%= link_to "Users", admin_users_path %></li> 
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
                Questions <b class ="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%# link_to "New question", new_admin_question_path %></li>
                <li class="divider"></li>
                <li><%# link_to "All questions", admin_questions_path %></li>             
              </ul>  
            </li> -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
                Options <b class ="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Score", admin_grades_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Setting", edit_admin_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %><li>              
              </ul>  
            </li>
          </ul>
        </nav>    
      <% else %> 
        <%= link_to "exam", current_user, id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
                <%=  current_user.name %> <b class ="caret"></b>
              </a>
              <ul class="dropdown-menu"> 
                <!-- <li><%# link_to "Change Password", edit_user_path(current_user) %></li> -->
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>              
              </ul>  
            </li>
          </ul> 
        </nav>   
      <% end %>           
    <% else %>
      <%= link_to "exam", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log in", login_path %></li>
        </ul> 
      </nav>   
    <% end %> 
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%# render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>